### ISSUE TITLE
새로운클래스 멀티샷

### ISSUE THREAD

**Issue by chipppppp** [noonmaru/heroes#119]
빌드하다가 봤는데 com.github.monun.multishot.jar이 새로 생긴거같더라구요
혹시 멀티샷에 대해서 아시는분이나 멀티샷 yml파일 알려주실수있나요?

**Comment by concertypin** [comment]
모든 클래스는 이런 식으로 yml 파일을 구성합니다.
```yml
abilities:
  sample:
    ability: 클래스명
```
