### ISSUE TITLE
능력을 2개이상 추가가 안되요

### ISSUE THREAD

**Issue by dragun1016** [noonmaru/heroes#125]
제가 여기나온 4개의 능력을 모두 적용하고 싶은데 부메랑 하나만 적용이 되요 wiki에 쓰여있는데로 했는데도 말이에요

**Comment by paring-chan** [comment]
https://github.com/noonmaru/psychics/wiki/%EC%9E%91%EC%84%B1%ED%95%98%EA%B8%B0 여기 가보시면 여러개 추가하는 예시도 있어요.

```yml
abilities:
  sample:
    ability: com.github.noonmaru.boomerang
  second-sample:
    ability: com.github.noonmaru.magic-arrow
```

+ 레포 이동했어요. https://github.com/monun/psychics
